/* Main.c file generated by New Project wizard
 *
 * Created:   mié. oct. 13 2021
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <main.h>

int main (void)
 {
    uint16_t d = 0;
    RCC->APB2ENR |= 0xFC;
    spi_init();
    LCDinit();
   // Write your code here
   while (1) {
    d= spi_receive();
    LCDsendChar(d);
   delay_ms(200);
  }
   return 0;
 }   
