/* Main.c file generated by New Project wizard
 *
 * Created:   mié. oct. 13 2021
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include <spi.h>
#include <lcd.h>
#include <stdint.h.>

int main (void)
 { 
     uint8_t  d =  0;
     spi_init();
    LCDinit();
   // Write your code here
   while (1){
     d = spi_transfer('A') ;
      LCDsendChar(d);
   }
   return 0;
 }   
